### ISSUE TITLE
The QA Acc of STAGE Model

### ISSUE THREAD

**Issue by Alchemistyui** [Lee-Ft/RHA#1]
Thanks for your great work! I'm still working on TVQA+ Dataset and trying to reproduce the result of STAGE. I noticed that in TVQA+ paper STAGE has  74.8 QA accuracy on test set, but in your paper it's 72.14, I'd like to know what's the difference here.

Thanks in advance.

**Comment by Lee-Ft** [comment]
Thanks for your attention. The results in our paper is reported as our reproduced experiment is based on official code offered by [STAGE](https://github.com/jayleicn/TVQAplus). In the README of that repo you can find some description like `After training, you should be able to get ~72.00% QA Acc, which is comparable to the reported number`. And I also asked the authors about this issue, and they replies that the source code was been cleaned so that the perfomance may be slightly worse. 

Please feel free to ask if you have any questions.

**Comment by Alchemistyui** [comment]
Thank you very much for your quick reply! 
Yes, I can get similar result on test set as you did, but still far from the authors. Your response makes me feel better, thanks again!

**Comment by Alchemistyui** [comment]
Sorry to bother you again, but would you mind sharing me with the reply from the author so that I can use it to support my reproduced result.

**Comment by Lee-Ft** [comment]
> Sorry to bother you again, but would you mind sharing me with the reply from the author so that I can use it to support my reproduced result.

As the email could be quite privacy, I have sent the key-part of content to your QQ mail on your GitHub page.

**Comment by Alchemistyui** [comment]
Thank you very much! I received it.
