### ISSUE TITLE
Ask for the pretrained model

### ISSUE THREAD

**Issue by Alchemistyui** [Lee-Ft/RHA#2]
Hi, thanks again for your great work!
I'd like to reproduce your model, but I got a little confused. Could you tell me what file should I run (run_main.sh or run_temp.sh)? And is there any pretrained weight shared?
Btw, I see 'create_full_dataset.py' to merge train and val set, do you use both to train the network?

Thanks in advance.

**Comment by Lee-Ft** [comment]
Sorry for late reply. 
1. You should run `run_temp.sh` with option `--add_local` like `bash run_temp.sh --add_local`. 
2. As for pretrained weight, I can not login to our server since I'm not at school for now, maybe I can offered it (maybe not worked for this code) when I am back to school and you still need it. 
3. And in my early experiment I did merge val and train set by `create_full_dataset.py`,but the performance is not better than train set only (I think I wasted a precious test chance for this setting). The results reported in paper is trained on train set only

Best regards.

**Comment by Alchemistyui** [comment]
Thank you very much for your reply and clarification. I'll try to train it by myself first, and I'll appreciate it if you can provide me the pretrained model when it's available.
